baseURL       = "https://boringlava.github.io/website/"
languageCode  = "en-us"
title         = "Mae Saslaw"
theme         = "ronu-hugo-theme"

[[menu.main]]
	name = "Curriculum vitae"
	url  = "/cv/"



  [params]
	authorNname = "Mae Saslaw"
	twitterURL  = "https://twitter.com/soilenjoyer"
	email       = "mae.saslaw@stonybrook.edu"
