baseURL       = "https://boringlava.github.io/"
title         = "Mae Saslaw"
theme         = "ronu-hugo-theme"
languageCode  = "en-us"
enableEmoji		= true

[[menu.main]]
	name = "Curriculum vitae"
	url  = "/cv/"
[[menu.main]]
  name = "Presentations"
  url  = "/presentations/"
[[menu.main]]
  name = "Presentations"
  url  = "/presentations/"

[params]
	authorNname = "Mae Saslaw"
	email       = "mae.saslaw@stonybrook.edu"
	description	= "Recent work"

[social]
  github  = "https://github.com/boringlava"
  twitter = "https://twitter.com/soilenjoyer"
